# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cli.ipynb.

# %% auto 0
__all__ = ['console', 'app', 'tui']

# %% ../nbs/00_cli.ipynb 3
import typer
from rich.console import Console
from .tui import TranscriptionTUI

# Console for rich formatting
console = Console()



# %% ../nbs/00_cli.ipynb 6
#| include: false
app = typer.Typer()

@app.command()
def tui():
    """Launch the interactive TUI for audio transcription."""
    tui_app = TranscriptionTUI()
    tui_app.run()

