# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cli.ipynb.

# %% auto 0
__all__ = ['console', 'app', 'tui', 'transcribe_last']

# %% ../nbs/00_cli.ipynb 3
import sys

import typer
from rich.console import Console

from .audio import AudioRecorder
from .transcription import WhisperTranscriber
from .tui import TranscriptionTUI
from .utils import copy_to_clipboard

# Console for rich formatting
console = Console()



# %% ../nbs/00_cli.ipynb 6
app = typer.Typer()

@app.command()
def tui():
    """Launch the interactive TUI for audio transcription."""
    tui_app = TranscriptionTUI()
    tui_app.run()

@app.command()
def transcribe_last():
    """Transcribe the most recently recorded audio file."""
    try:
        recorder = AudioRecorder()
        audio_file_path = recorder._get_audio_file_path()
        if not audio_file_path.exists():
            console.print(
                "❌ [bold red]No previous recording found. Record audio first by running 'hns' without --last flag.[/bold red]"
            )
            sys.exit(1)

        transcriber = WhisperTranscriber()
        transcription, elapsed_time = transcriber.transcribe(audio_file_path)

        copy_to_clipboard(transcription, elapsed_time)

    except (RuntimeError, ValueError) as e:
        console.print(f"❌ [bold red]{e}[/bold red]")
        sys.exit(1)
    except Exception as e:
        console.print(f"❌ [bold red]Unexpected error: {e}[/bold red]")
        sys.exit(1)


