# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_config.ipynb.

# %% auto 0
__all__ = ['TuiWriterConfig', 'get_cfg']

# %% ../nbs/01_config.ipynb 3
#| include: false
from dataclasses import dataclass
from fastcore.all import *
from fastcore.xdg import *
from typing import get_type_hints

# %% ../nbs/01_config.ipynb 4
#| include: false
_tui_writer_home_dir = 'tui_writer'
_tui_writer_cfg_name = 'tui_writer.conf'

# %% ../nbs/01_config.ipynb 5
#| include: false
def _cfg_path(): return xdg_config_home() / _tui_writer_home_dir / _tui_writer_cfg_name

# %% ../nbs/01_config.ipynb 8
#| include: false
@dataclass
class TuiWriterConfig:
    openai_key: str = ''
    anthropic_key: str = ''
    gemini_key: str = ''
    last_provider: str = ''
    last_model: str = ''

# %% ../nbs/01_config.ipynb 10
#| include: false
def get_cfg():
    path = _cfg_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    _types = get_type_hints(TuiWriterConfig)
    return Config(
        path.parent,
        path.name,
        create=asdict(TuiWriterConfig()),
        types=_types,
        inline_comment_prefixes=('#')
    )

# %% ../nbs/01_config.ipynb 11
#| include: false
def get_cfg():
    path = _cfg_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    _types = get_type_hints(TuiWriterConfig)
    return Config(
        path.parent,
        path.name,
        create=asdict(TuiWriterConfig()),
        types=_types,
        inline_comment_prefixes=('#')
    )
