# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/tui_template.ipynb.

# %% auto 0
__all__ = ['StatusCard', 'TUITemplate']

# %% ../nbs/tui_template.ipynb 3
from textual.app import App, ComposeResult
from textual.containers import Container, Vertical, Grid, HorizontalGroup, Center
from textual.widgets import Header, Footer, Static, Digits, Button

# %% ../nbs/tui_template.ipynb 4
"""
Unicode for later use: ⭕🔴🔵🌀
Custom composed widgets: StatusCard
"""
class StatusCard(HorizontalGroup):
    """Beautiful status card with recording information."""
    def compose(self) -> ComposeResult:
        yield Static("● RECORDING", classes="status")
        with Center():
            yield Digits("2:56.32", id="status-time", classes="status")
        with HorizontalGroup(classes="card_button"):
            yield Button.error("REC")
            yield Button.success("SAVE")

# %% ../nbs/tui_template.ipynb 5
class TUITemplate(App):
    """Standalone TUI template for design testing."""

    TITLE = "TUI Writer"
    SUB_TITLE = "Design Template"
    CSS = """
    Screen {
        background: $surface;
    }

    StatusCard {
        margin-top: 1;
        width: 50%;
        layout: grid;
        grid-size: 1 3;
        background: $boost;
        border: tall $primary;
    }

    .status {
        content-align: center middle;
    }

    #status-time {
        border: double green;
        width: auto;
        padding: 0 1;
        margin: 1 0;
    }

    .card_button{
        align: center middle;
    }
        
    Header {
        background: $primary;
    }
    """

    BINDINGS = [
        ("q", "quit", "Quit"),
        ("d", "toggle_dark", "Toggle dark mode"),
    ]
    
    def compose(self) -> ComposeResult:
        header = Header(show_clock=True)
        header.tall = True
        yield header

        with Center():
            yield StatusCard()


        yield Static("Main content goes here", id="main-content")


        yield Footer()

    def action_toggle_dark(self) -> None:
        """An action to toggle dark mode."""
        self.theme = (
            "textual-dark" if self.theme == "textual-light" else "textual-light"
        )

# %% ../nbs/tui_template.ipynb 6
if __name__ == "__main__":
    app = TUITemplate()
    app.run()
