# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/tui_template.ipynb.

# %% auto 0
__all__ = ['TEXTUAL_CSS', 'TimeDisplay', 'StatusCard', 'InfoCard', 'TranscriptField', 'TextField', 'RecordingState',
           'TUITemplate']

# %% ../nbs/tui_template.ipynb 4
TEXTUAL_CSS = """
    Screen {
        background: $surface;
    }
    Header {
        background: $primary;
    }

    StatusCard {
        width: auto;
        row-span: 2;
        border: solid $primary;
        border-title-align: center;
        height: 100%;
        padding: 1 0;
    }

    InfoCard {
        width: auto;
        border: solid #6b7280;
        border-title-align: center;
        height: 100%;
        column-span: 3;
        padding: 1;
    }

    TranscriptField {
        width: auto;
        border: solid $warning;
        border-title-align: center;
        height: 100%;
        column-span: 3;
        padding: 1;
    }
    TranscriptField TextArea {
        border: none;
    }

    #top-cards {
        layout: grid;
        grid-size: 4 2;
        grid-rows: 1fr;
        grid-columns: 1fr;
        grid-gutter: 1;
        margin: 1;
        height: 40vh;
    }

    TextField {
        width: 100%;
        margin: 1;
        padding: 1;
        border: solid #8b5cf6;
        border-title-align: center;
        height: 50vh;
    }

    #status {
        content-align: center middle;
    }

    #status-time {
        border: double green;
        width: auto;
        padding: 0 1;
        margin: 1 0;
    }

    #media-controls {
        dock: bottom;
        align: center middle;
    }

    #media-controls Button {
        min-width: 20;
    }

    #pause,
    #resume,
    #stop {
        display: none;
    }

    .active #start {
        display: none;
    }
    .active #pause,
    .active #stop {
        display: block;
    }
    .active #status {
        color: $error;
    }

    .paused #start {
        display: none;
    }
    
    .paused #status {
        color: $warning;
    }

    .paused #resume,
    .paused #stop {
        display: block;
    }
"""

# %% ../nbs/tui_template.ipynb 6
from time import monotonic
from enum import Enum
from textual import on
from textual.app import App, ComposeResult
from textual.reactive import reactive
from textual.containers import Container, VerticalGroup, Grid, HorizontalGroup, CenterMiddle
from textual.widgets import Header, Footer, Static, Digits, Button, Label, TextArea

# %% ../nbs/tui_template.ipynb 8
class TimeDisplay(Digits):
    """Custom time display widget"""
    
    accumulated_time = 0
    time_elapsed = reactive(0)

    def on_mount(self):
        self.update_timer = self.set_interval(
            1 / 60, 
            self.update_time_elapsed,
            pause=True    
        )


    def update_time_elapsed(self):
        self.time_elapsed = self.accumulated_time + (monotonic() - self.start_time)

    def watch_time_elapsed(self):
        time = self.time_elapsed
        time, seconds = divmod(time, 60)
        hours, minutes = divmod(time, 60)
        time_string = f"{hours:02.0f}:{minutes:02.0f}:{seconds:05.2f}"
        self.update(time_string)

    def start(self):
        """Start keeping track of time elapsed"""
        self.start_time = monotonic()
        self.update_timer.resume()
    
    def pause(self):
        """Pause keeping track of time elapsed"""
        self.accumulated_time = self.time_elapsed
        self.update_timer.pause()

    def stop(self):
        """Stop/reset the time elapsed"""
        self.start_time = monotonic()
        self.accumulated_time = 0
        self.time_elapsed = 0
        self.update_timer.pause()

class StatusCard(Label):
    """Recording status card with controls"""
    status_text = reactive("● STANDBY")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.border_title = "Recording Status"

    def start_transcript(self):
        self.add_class("active")
        self.status_text = "● RECORDING..."

    def pause_transcript(self):
        self.remove_class("active")
        self.add_class("paused")
        self.status_text = "⏸ PAUSED"

    def resume_transcript(self):
        self.remove_class("paused")
        self.add_class("active")
        self.status_text = "● RECORDING..."

    def stop_transcript(self):
        self.remove_class("paused")
        self.remove_class("active")
        self.status_text = "● STANDBY"

    def watch_status_text(self):
        """Update the status display when status_text changes"""
        if self.is_mounted:
            self.query_one("#status").update(self.status_text)

    def compose(self) -> ComposeResult:
        yield Static(self.status_text, id="status")
        with CenterMiddle():
            yield TimeDisplay("0:00:00", id="status-time")
        with HorizontalGroup(id="media-controls"):
            yield Button.error("● REC <space>", id="start")
            yield Button.success("⏸ PAUSE <space>", id="pause")
            yield Button.warning("▶ RESUME <space>", id="resume")
            yield Button("◼ STOP", id="stop")
    
class InfoCard(Label):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.border_title = "Info"

    def compose(self) -> ComposeResult:
        yield Static("Model: Whisper-Tiny")
        yield Static("Microphone: Default System Mic")

class TranscriptField(Label):

    transcript_block = reactive("", always_update=True)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.border_title = "Last Transcript-block"

    def compose(self) -> ComposeResult:
        yield TextArea("Change the name to Jens William", read_only=True, show_cursor=False)


class TextField(Label):

    content = reactive("Default text\n")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.border_title = "Text Field"

    def compose(self) -> ComposeResult:
        yield TextArea(
            "",
            read_only=True,
            show_line_numbers=True,
            show_cursor=False,
            id="main-textarea"
        )

    def watch_content(self) -> None:
        """This method is called whenever 'content' changes"""
        if self.is_mounted:
            textarea = self.query_one("#main-textarea")
            textarea.text = self.content
            textarea.refresh()  # This forces the TextArea to redraw!
            textarea.scroll_end()

# %% ../nbs/tui_template.ipynb 10
class RecordingState(Enum):
    STANDBY = "standby"
    RECORDING = "recording"
    PAUSED = "paused"

class TUITemplate(App):
    """Standalone TUI template for design testing."""

    TITLE = "TUI Writer"
    SUB_TITLE = "Design Template"
    CSS = TEXTUAL_CSS

    BINDINGS = [
        ("q", "quit", "Quit"),
        ("space", "toggle_status", "Start/Pause/Resume Recording"),
        ("l", "list_models", "List Models")
    ]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.recording_state = RecordingState.STANDBY

    def compose(self) -> ComposeResult:
        header = Header(show_clock=True)
        header.tall = True
        yield header

        with Container(id="top-cards"):
            yield StatusCard()
            yield InfoCard()  # Add an Info widget here
            yield TranscriptField()
        yield TextField()
        yield Footer()

    # Action methods triggered by key bindings, refers to button-methods
    def action_toggle_status(self) -> None:
        """An action to toggle recording status."""
        if self.recording_state == RecordingState.RECORDING:
            self.pause_recording()
        elif self.recording_state == RecordingState.PAUSED:
            self.resume_recording()
        else: # RecordingState.STANDBY
            self.start_recording()
    
    @on(Button.Pressed, "#start")
    def start_recording(self):
        """Centralized method to start recording"""
        self.recording_state = RecordingState.RECORDING

        status_card = self.query_one(StatusCard)
        time_display = self.query_one(TimeDisplay)

        status_card.start_transcript()
        time_display.start()

    @on(Button.Pressed, "#pause")
    def pause_recording(self):
        """Central method to pause recording"""
        self.recording_state = RecordingState.PAUSED

        status_card = self.query_one(StatusCard)
        time_display = self.query_one(TimeDisplay)
        
        status_card.pause_transcript()
        time_display.pause()
    
    @on(Button.Pressed, "#resume")
    def resume_recording(self):
        """Central method to resume recording"""
        self.recording_state = RecordingState.RECORDING

        status_card = self.query_one(StatusCard)
        time_display = self.query_one(TimeDisplay)

        status_card.resume_transcript()
        time_display.start()

    @on(Button.Pressed, "#stop")
    def stop_recording(self):
        """Central method to stop recording"""
        self.recording_state = RecordingState.STANDBY

        status_card = self.query_one(StatusCard)
        time_display = self.query_one(TimeDisplay)

        status_card.stop_transcript()
        time_display.stop()

# %% ../nbs/tui_template.ipynb 21
if __name__ == "__main__":
    app = TUITemplate()
    app.run()
