# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/tui_template.ipynb.

# %% auto 0
__all__ = ['TUITemplate']

# %% ../nbs/tui_template.ipynb 3
from textual.app import App, ComposeResult
from textual.containers import Container
from textual.widgets import Header, Footer, Static

# %% ../nbs/tui_template.ipynb 4
class TUITemplate(App):
    """Standalone TUI template for design testing."""

    CSS = """
    Screen {
        align: center middle;
    }
    """

    BINDINGS = [("q", "quit", "Quit")]
    
    def compose(self) -> ComposeResult:
        yield Header()
        yield Static("TUI Template - Design Mode", id="main")
        yield Footer()

# %% ../nbs/tui_template.ipynb 5
if __name__ == "__main__":
    app = TUITemplate()
    app.run()
