# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_utils.ipynb.

# %% auto 0
__all__ = ['console', 'format_duration', 'copy_to_clipboard', 'is_cuda_available']

# %% ../nbs/03_utils.ipynb 3
import pyperclip
from typing import Optional
from rich.console import Console

# Console for rich formatting
console = Console()


# %% ../nbs/03_utils.ipynb 4
def format_duration(seconds: float) -> str:
    """Format duration in seconds to HH:MM:SS or MM:SS format.

    This utility function converts a duration in seconds to a human-readable
    string format. It intelligently handles both short and long durations
    by conditionally including hours.

    Args:
        seconds: Duration in seconds (can be float for precision)

    Returns:
        Formatted duration string

    Examples:
        >>> format_duration(125.7)
        '02:05'
        >>> format_duration(3723.8)
        '1:02:03'
        >>> format_duration(59.9)
        '00:59'
    """
    total_seconds = int(seconds)
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60

    if hours > 0:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    else:
        return f"{minutes:02d}:{secs:02d}"


# %% ../nbs/03_utils.ipynb 5
def copy_to_clipboard(text: str, elapsed_time: Optional[float] = None):
    """Copy transcribed text to system clipboard and display results.

    This function serves as the final step in the transcription pipeline,
    making the results immediately accessible to the user through multiple
    channels: system clipboard for easy pasting, and visual confirmation
    in the terminal interface.

    Args:
        text: The transcribed text content to copy
        elapsed_time: Optional processing time for performance feedback

    The function provides immediate visual feedback about the transcription
    success and performance metrics, ensuring users understand both the
    result quality and system performance.
    """
    pyperclip.copy(text)
    if elapsed_time:
        console.print(f"✅ [bold green]Transcribed and copied to clipboard in {elapsed_time:.1f}s![/bold green]")
    else:
        console.print("✅ [bold green]Transcribed and copied to clipboard![/bold green]")
    console.print(f"\n{text}")


# %% ../nbs/03_utils.ipynb 6
def is_cuda_available() -> bool:
    """Check if CUDA is available for GPU acceleration."""
    try:
        import torch
        return torch.cuda.is_available()
    except ImportError:
        return False
